var dnaString = "AAAATATGTGTATCAATGCCGCTATCATCCCGAGCTCCTCTTAAGTCGAGGGTGAGCCAGAATAGGCCCGTACGCGGGATCAGGCCGCGAACACCCGGTCTGGGTCGAAAGAGTCTGTACAGGCTTGTTCTAGATGCGCTAAATTGTTACGTTCAAATAAGTTAGGTTTCATATCAGCACGGTCTATGCTCGCATATGATCACGCCCAAGACAGTTTTTTTAATCACGACACACGACCCTAGTCGAAAGAAGTAGTCATTTGGCCGATGGGTCACATGTCAAGCGTACACTAGTGTGAGACAGCAGACGACACTACAGTACTGACATACCCCGTTGGACCAGCAGCCGGGTTTTAACCCATTGCTCAACGCTAGGTAAAAGTGACGGTACACTGATATGTGGCCAGGAGTGATAAGGGGTCATGACTGAAGGCGGAGCCTTAAAAACAAAGCGTCACGTTATACAGCTTGCGAGCCCACTATATGTCATGGATTATTGCCGGGAAGAGACTCTGGTCAGCGCTGCCATGGTAGGGCCGAGATTGCTCTAATTCAGGGAAGCACAACGTGACCCTACTGGACAAGACTAACCTGGACCCGGGTTTCCGTACCTAATACACCCATAGGTGGTGTAGTTAGGGGCGAATTGGCACCTGTAGACGTCACGCGACTGGACAGCCGTCCTTCCCCATTTCTAACCTTGCCTGAGAAAGCCCGACGACCATGGAAACAGGTCCTATCATGGTCGCAAACAACCCTCCCCTAAACGATGTCATTCTCCAGGTTGTAGCCTCATGTATTATCCATGCATGCTTTGATGTAACAAGAAGTGCACAGGAGCCAGTACCCTCGCACCGCGGATTTCGTATCGTGACAGAATGCCGTCGTGAAACTGGTTGG";
var a = 0, c = 0, g = 0, t = 0;

var i;
for (i = 0; i < dnaString.length; i += 1) {
    var ch = dnaString.charAt(i);
    switch (ch) {
    case 'A':
        a += 1;
        break;
    case 'C':
        c += 1;
        break;
    case 'G':
        g += 1;
        break;
    case 'T':
        t += 1;
        break;
    }
}

var document;
var dnaSolution = document.getElementById('dna-solution');
dnaSolution.innerHTML = (a + " " + c + " " + g + " " + t);