dnaString = "AAAATATGTGTATCAATGCCGCTATCATCCCGAGCTCCTCTTAAGTCGAGGGTGAGCCAGAATAGGCCCGTACGCGGGATCAGGCCGCGAACACCCGGTCTGGGTCGAAAGAGTCTGTACAGGCTTGTTCTAGATGCGCTAAATTGTTACGTTCAAATAAGTTAGGTTTCATATCAGCACGGTCTATGCTCGCATATGATCACGCCCAAGACAGTTTTTTTAATCACGACACACGACCCTAGTCGAAAGAAGTAGTCATTTGGCCGATGGGTCACATGTCAAGCGTACACTAGTGTGAGACAGCAGACGACACTACAGTACTGACATACCCCGTTGGACCAGCAGCCGGGTTTTAACCCATTGCTCAACGCTAGGTAAAAGTGACGGTACACTGATATGTGGCCAGGAGTGATAAGGGGTCATGACTGAAGGCGGAGCCTTAAAAACAAAGCGTCACGTTATACAGCTTGCGAGCCCACTATATGTCATGGATTATTGCCGGGAAGAGACTCTGGTCAGCGCTGCCATGGTAGGGCCGAGATTGCTCTAATTCAGGGAAGCACAACGTGACCCTACTGGACAAGACTAACCTGGACCCGGGTTTCCGTACCTAATACACCCATAGGTGGTGTAGTTAGGGGCGAATTGGCACCTGTAGACGTCACGCGACTGGACAGCCGTCCTTCCCCATTTCTAACCTTGCCTGAGAAAGCCCGACGACCATGGAAACAGGTCCTATCATGGTCGCAAACAACCCTCCCCTAAACGATGTCATTCTCCAGGTTGTAGCCTCATGTATTATCCATGCATGCTTTGATGTAACAAGAAGTGCACAGGAGCCAGTACCCTCGCACCGCGGATTTCGTATCGTGACAGAATGCCGTCGTGAAACTGGTTGG";
a = 0;
c = 0;
g = 0;
t = 0;

for (i = 0; i < dnaString.length; i++){
  ch = dnaString.charAt(i);
  switch(ch) {
	case 'A':
	  a += 1;
	  break;
	case 'C':
	  c += 1;
	  break;
	case 'G':
	  g += 1;
	  break;
	case 'T':
	  t += 1;
	  break;  
  }
}

document.write(a + " " + c + " " + g + " " + t);
