dnaString = "CGGCAAACATTGCCTCATGGGAGGTAAGATTTAATCTATAAGAGAACAGGACCTACGATGCGCCGGACAGGCAGTGCTCCGCGGACATTTAAATTTAGACTCTGCATTCCAGATGCACTCACAGCGCCCACACGCTAAGGGCCAGTTTATAGACGTCGGATTTGTCGGTCGACGTCATTGCAGGCGGGTCAGGTGTCATTCTCGGCAACGAAGGCCTCCTACGCTGCGAACGCTCAATACGACTGTTCCGACGTTGTACTGACGACGAGAGCCTAGGTGTCGCAGGTCAATCTATCCGTGGAATAGGCTAGCGTACCGAATGCCCTGATTGACAATTCCAAGATAGCGAATGGCATTGGGAGAAGACGGCAATTGTTTTGACGAAGGTAATGAAGTCAGGAAAACAAGTGGTCCATACTTCCCACTTAGCTTGGCGTACAAGTGTTCCCACTAGCGATAAAGCTCCAACGACTTCCTTAGTTTCACTCGCAGCTGGAGGTCTAAACATCGCGGGTCAACAGGTTCTGGTCGGATGATAGGGGTCTAAGACAGGGGGGTCCGTTTTGCAACCCTAACAGGCATAAAGCTTTTCCGATTCATTTTGCACTACCGATTTTAAGCCATTCTTCCAAGGTCAGCGAACGGCCGAAGTAGGGATAATAATCATGCTTGTACCGAGCCGCCCCGTTTCCCATCTAAGTACGCCCCAAACCCCTCGGAGCACTCATAGTTTATCAATCAAAATGACACTCAGACTCGATGCGTGATTGATTCCGGTGCTTTAAGCGGAAATGTAGCTTACGCTTGGCTCTGCGGTATGTTCGCTTATTTCGTTCTTATATGGAGATCCGCTGACACAAGACGGCAAATACAGTCTGTATACCGTGGGCTCAA";
reverseCompliment = "";

for (i = dnaString.length; i >= 0; i--) {
  ch = dnaString.charAt(i);
  switch(ch) {
	case 'A':
	  reverseCompliment += 'T';
	  break;
	case 'C':
	  reverseCompliment += 'G';
	  break;
	case 'G':
	  reverseCompliment += 'C';
	  break;
	case 'T':
	  reverseCompliment += 'A';
	  break;  
  }
}

document.write(reverseCompliment);
