var stringS = "CGGGCGTATCGCTTGGCGTATCGGCGTATCGGCGTATCTAGGGCGTATCGGCGTATAGGCGTATCCGTTGGCGTATGGCGTATGGGCGTATGGCGTATCGGCGTATCTACACAGGCGTATAGGTGTGGCGTATGGCGTATCCATGGCGTATGGGCGTATCTAGGCGTATGTAAACCCCGAGGGGAGGCGTATGGCGTATTGGATATAGGCGTATGGGCGTATGGCGTATTCGTCGGCGTATGGCGTATGGCGTATGGCGTATAACGGCGTATGGCGTATGGCGTATGGCGTATGATATTAGCGGGCGTATCTTTGGCGTATTAGGCGTATAGCTCTCTGGCGTATGCAGGCGTATAGGCGTATAAGGCGTATGGCGTATGGCGTATTAGCAGGCGTATAGCTGGCGTATTCCTTGGGCGTATGGCGTATGGCGTATGGCGTATTGGCGTATGGCGTATCGGATGGGCGTATGTATAAATGGCGTATCCAACGGGCGTATTCCGGCGTATAAGGGGCGTATAAGGCGTATTGCATCCGGCGTATCGGGCGTATTGGGCGTATGAAGTCTACCGGGCGTATCGGCGTATCTCCTCCGGCGTATGGCGTATTCCAAATCTGGCGTATGGCGTATGGGCGTATGGCGTATGGCGTATGGGCTTCGGCGTATGGCGTATCTCGGCGTATAGGCGTATAGGCGTATGAGGCGTATGGCGTATGGCGTATTAGGCGTATGGGCGTATTTGGCGTATCGCTGGCGTATAAACGGCGTATGGCGTATGTAAGTTGATGTATCCGGCGTATTCGGACGGGCGTATGGCGTATTAGGCGTATGTCGGCGTAT";
var stringT = "GGCGTATGG";

var i;
var matches = "";

for (i = 0; i <= (stringS.length - stringT.length); i += 1) {
    if (stringS.charAt(i) !== stringT.charAt(0)) {
        continue;
    }

    var j;
    var matchSoFar = true;
    for (j = 0; j < stringT.length; j += 1) {
        if (stringS.charAt(i + j) !== stringT.charAt(j)) {
            matchSoFar = false;
            continue;
        }
    }
    if (matchSoFar) {
        matches = matches + (i + 1).toString() + " ";
    }
}

var document;
var subsSolution = document.getElementById('subs-solution');
subsSolution.innerHTML = matches;